### PR TITLE
cargo-miri: support running unit tests for libraries as well as test binaries

### PR DESCRIPTION
**Pull request by apoelstra**

### CODE REVIEW

**Comment by apoelstra** [comment]
This currently won't work because of #479 but it can be tested by hacking in a separate attribute that Miri detects rather than `#[test]`.

**Comment by RalfJung** [comment]
TBH, I don't actually understand this code, but if CI is happy it can't be worse than the old one.^^ What do you think @oli-obk?

**Comment by apoelstra** [comment]
To clarify -- for tests we pass `--test <testname> -- <rustc args>` to cargo. For libraries we pass `-- --test <rustc args>` to cargo. That is, we're moving `--test` from a cargo argument (find an appropriate test binary, compile it, etc etc) to a rustc argument (compile the test runner for whatever you're already being told to compile).

**Comment by RalfJung** [comment]
If you you jet down some comments into the code, that'd be nice. :D

**Pull request merged**
