### PR TITLE
only allow 0-offset on integer pointers

### PR DESCRIPTION
**Pull request by RalfJung**
Triggered by https://github.com/rust-lang/rust/issues/54857

### CODE REVIEW

**Comment by oli-obk** [comment]
Integer pointers to non-zsts are normal on embedded. This would make most embedded code UB

**Comment by RalfJung** [comment]
That's platform-specific. On embedded, it might also be okay to do `(0x400usize as *mut u32) = 14`, and yet miri will always flag that as UB.

Currently we can only say whether your code is okay on *all* platforms (of the given target). We cannot test code that makes specific extra assumptions about e.g. allocations existing at fixed locations.

**Comment by RalfJung** [comment]
> is something you can easily replicate by casting to an int, adding and casting back

Supporting that is tracked in https://github.com/solson/miri/issues/224.

> something that you can do without emulating the hardware (writing/reading to/from integer addresses needs such emulation)

We are not talking about hardware though, but about an abstract machine where whether an allocation exists somewhere makes a difference. In that abstract machine, the offset can *not* be emulated without further knowledge.

**Comment by RalfJung** [comment]
> That said, there's probably many things that go wrong when looking at embedded. I'll rather address this once I have a basic emulation setup and a bunch of tests

Wow, you have plans there?
But yes, an emulation setup that can fake the presence of non-ZST allocations at fixed addresses (including read/write accesses) should fix this properly.

**Pull request merged**
