### PR TITLE
Update for allcator API, simplify reallocate

### PR DESCRIPTION
**Pull request by RalfJung**
So nice to have a test suite :)

### CODE REVIEW

**Comment by RalfJung** [comment]
> So nice to have a test suite :)

... even more so when it unexpectedly fails on you... *oops*

**Comment by oli-obk** [comment]
hehe not your fault: `#![feature(associated_consts)]` is stable

**Comment by RalfJung** [comment]
Yeah just noticed. Preparing a commit to be added here to fix that.

**Comment by RalfJung** [comment]
Okay there's lots of weird test failures now...
```
thread '[mir-opt] mir-opt/issue-33387.rs' panicked at 'explicit panic', /home/r/.cargo/registry/src/github.com-1ecc6299db9ec823/compiletest_rs-0.2.8/src/runtest.rs:2374:8

---- [mir-opt] mir-opt/ints.rs stdout ----

error: compilation failed!
status: signal: 11
command: target/debug/miri tests/run-pass/ints.rs -L /tmp --target=x86_64-unknown-linux-gnu -Z dump-mir=all -Z mir-opt-level=3 -Z dump-mir-dir=/tmp/ints -L /tmp/ints.stage-id.mir-opt.libaux -C prefer-dynamic -o /tmp/ints.stage-id
stdout:
------------------------------------------

------------------------------------------
stderr:
------------------------------------------

------------------------------------------

thread '[mir-opt] mir-opt/ints.rs' panicked at 'explicit panic', /home/r/.cargo/registry/src/github.com-1ecc6299db9ec823/compiletest_rs-0.2.8/src/runtest.rs:2374:8
```

**Comment by oli-obk** [comment]
try running the full command `target/debug/miri tests/run-pass/ints.rs -L /tmp --target=x86_64-unknown-linux-gnu -Z dump-mir=all -Z mir-opt-level=3 -Z dump-mir-dir=/tmp/ints -L /tmp/ints.stage-id.mir-opt.libaux -C prefer-dynamic -o /tmp/ints.stage-id`

We've had rustc bugs before, e.g. with `-Z dump-mir=all`

**Comment by RalfJung** [comment]
Something is definitely odd here; I didn't change anything and now the number of failures is down from 50 to 20...

**Comment by RalfJung** [comment]
All right, all tests pass. Since fixing things for latest nightly also affected the allocator code, I added it to the same PR; I hope that's fine.

**Comment by oli-obk** [comment]
Cool thanks! looks like you ran into a nightly release in the middle of this PR ^^

**Pull request merged**
