### PR TITLE
make sure that StorageDead invalidates the backing store

### PR DESCRIPTION
**Pull request by RalfJung**

### CODE REVIEW

**Comment by oli-obk** [comment]
this is more than just StorageDead, this also acts on function termination.

We probably need to implement this with just scopes and no function calls (although the latter is good as an additional sanity check)

**Comment by RalfJung** [comment]
I do not understand. Here the function still runs when the dangling pointer is used.

The only thing invalidating it is `StorageDead`, right?

**Comment by oli-obk** [comment]
lol sorry, I didn't read that code right. Would still have worked without the functions, but yea, you're right.

**Comment by RalfJung** [comment]
> Would still have worked without the functions

True, I imagined those to be in a different crate for the sake of the example.

**Pull request merged**
