### PR TITLE
remove our array drop glue and use rustc's instead

### PR DESCRIPTION
**Pull request by RalfJung**
The test suite will fail until <https://github.com/rust-lang/rust/pull/42369> gets merged.

### CODE REVIEW

**Comment by RalfJung** [comment]
I just foubd out about `unrelated_ptr_ops`, so I suppose I should re-work this PR to hook into said method instead.

**Comment by oli-obk** [comment]
Huh? Why? It will be used automatically when the rustc PR of yours is merged

**Comment by RalfJung** [comment]
What "it"? This PR currently handles the new `Offset` MIR binary operation very differently from all other binary operations. The reason for this was that I thought that `EvalContext::binop_with_overflow` cannot work with pointer values, but actually now I realized that it can, and hence `Offset` should be implemented in there, I feel.

**Comment by RalfJung** [comment]
Also, the rustc PR just got merged :)

**Comment by oli-obk** [comment]
Ooh that makes total sense

**Comment by eddyb** [comment]
@RalfJung `Offset` and the `offset` intrinsic actually have "inbounds" semantics, which means they're UB if they go outside of the bounds of the allocation. `arith_offset` and addition don't.

Oh, I see, `Offset` is "just" another MIR binop, so yeah, handling it with other binops is fine.
(but it needs to have the same implementation as the `offset` intrinsic)

**Comment by oli-obk** [comment]
Both locations can probably call the same function with the same impl

**Comment by RalfJung** [comment]
> Offset and the offset intrinsic actually have "inbounds" semantics, which means they're UB if they go outside of the bounds of the allocation. arith_offset and addition don't.

That is however not what the intrinsic currently implements -- and the drop glue in rustc *does* create an out-of-bounds pointer (namely, a one-past-the-end-pointer) with this.

**Comment by eddyb** [comment]
@RalfJung [one-past-the-end is explicitly allowed](http://llvm.org/docs/GetElementPtr.html#what-happens-if-an-array-index-is-out-of-bounds).

**Comment by RalfJung** [comment]
All right. Still, my point stands that miri doesn't implement this. The following code reaches the panic:
```rust
fn main() {
    let v = [0i8; 4];
    let x = &v as *const _ as *const i8;
    let x = unsafe { x.offset(5) };
    panic!("this should never print: {:?}", x);
}
```

**Comment by eddyb** [comment]
@RalfJung Well that is a bug and should be fixed. How does it not get hit with slice iterators?!
That is, I expect `v.iter()` to do the same `.offset(5)` operation. Or maybe it points to the last element instead? Not sure.

**Comment by RalfJung** [comment]
I expect iterators to do `.offset(len)`, which would be `4` above, so that should be fine.

**Comment by eddyb** [comment]
Aaah oops I misread! `.offset(4)` *is* one-past-the-end. As in, it's the first byte not in the allocation.

**Comment by RalfJung** [comment]
All right, I implemented `Offset` like the other binary operators and made it share code with the intrinsic. I will submit a separate PR with various other pointer-related fixes, including fixing both the `Offset` binop and the intrinsic to do bounds checking.

**Comment by RalfJung** [comment]
Ah, something interesting came up. The new array drop glue (the one with my patch) uses "offset 0" on empty arrays/slices. These pointers can point anywhere. So the output is the same as the input, but that may not be a valid pointer. I am now (in a branch I will submit once this one got merged) treating "Offset by 0" as a special case, not checking bounds here -- but I am not sure if this actually matches LLVM..

**Comment by eddyb** [comment]
If the allocation is empty, offset by zero is one-after-the end.

**Comment by RalfJung** [comment]
True, but a zero-sized allocation is not really anything that exists, right? Is it defined in LLVM to pass a ZST-pointer (as in, "some random address") and offset 0 to an `inbounds` GEP? That pointer doesn't correspond to any allocation, so it's hardly "one-after-the-end".

**Comment by RalfJung** [comment]
Anyway, that's for the other PR, the one that actually implements the currently missing bounds checks. What about this one?

I rebased onto current master so the tests should pass now.

**Comment by RalfJung** [comment]
Hm, that test failure is odd. The `Offset` intrinsic is used on two `Bytes` arguments...

**Comment by RalfJung** [comment]
What do you mean, "want just integers"?

**Comment by RalfJung** [comment]
All right, the tests should now pass. I changed `binary_op` to catch the `Offset` binop early, so that it is handled in a more unified way.

**Pull request merged**
