### PR TITLE
Revert "Revert "rustup to rustc 1.15.0-dev (ace092f56 2016-12-13)""

### PR DESCRIPTION
**Pull request by solson**
Reverts the revert, #94, bringing #93 back into master.

### CODE REVIEW

**Comment by oli-obk** [comment]
Compiletest seems to be broken now

**Comment by solson** [comment]
Yeah, what happened there?

**Comment by solson** [comment]
I get the same failure locally.

**Comment by oli-obk** [comment]
Update to 0.2.5

**Comment by oli-obk** [comment]
It was released two hours ago

**Comment by solson** [comment]
I'm on it.

**Pull request merged**
