### PR TITLE
Detect modifications of immutable memory

### LINKED ISSUE #51: Forbid modification of constant memory and vtables
Right now it's possible to create a pointer to an immutable static or a constant and modify that memory. It's not a problem for constants yet, because we don't cache constants so far.

### PR DESCRIPTION
**Pull request by oli-obk**
fixes #51 

is there anything other than promoteds, constants, statics and vtables that should be immutable?

### CODE REVIEW

**Comment by eddyb** [comment]
@oli-obk It's not possible to borrow const/promoted directly from runtime code because they're not lvalues. Instead, *all* temp borrows in const/promoted create `'static` memory (immutable, usually).

**Comment by oli-obk** [comment]
Well I meant whether we have any other memory blobs that get put into program memory instead of data, so miri would have to treat them as immutable

**Comment by solson** [comment]
This still appears to contain the commits from the vtables PR. Not sure if that matters.

**Comment by oli-obk** [comment]
rebased

**Pull request merged**
