### PR TITLE
Get the test suite working inside the rustc test suite

### PR DESCRIPTION
**Pull request by oli-obk**
I had to weave some env vars over from rustc, but it works now both within rustc and here.

### CODE REVIEW

**Comment by RalfJung** [comment]
What exactly is it that used to not work and works with this? I don't understand what "inside the rustc test suite" means.

**Comment by RalfJung** [comment]
Ah, I see. This is for <https://github.com/rust-lang/rust/pull/43628>. Looks good!

**Comment by RalfJung** [comment]
Of course, eventually, we will want to run miri on the entire rustc testsuite itself, not just on in its rather small testsuite. :)

**Comment by oli-obk** [comment]
> Of course, eventually, we will want to run miri on the entire rustc testsuite itself, not just on in its rather small testsuite. :)

for that we need a way to mark tests as "miri will always fail on this"

**Pull request merged**
