### PR TITLE
Enable more validation tests

### PR DESCRIPTION
**Pull request by RalfJung**
https://github.com/rust-lang/rust/issues/43457 got fixed :)

### CODE REVIEW

**Comment by oli-obk** [comment]
I have no idea why some of the tests are still failing... It works locally, but doesn't work on travis.

**Comment by oli-obk** [comment]
Let's turn validation back off for these tests.

**Comment by RalfJung** [comment]
Thanks, that looks right. I have idea for how to fix #296; once I implemented that, I can reevaluate these tests.

**Comment by RalfJung** [comment]
The one thing I do not understand at all is `undefined_byte_read.rs`. That one still works on master (the CRON job just accepted it), but it failed here?

**Comment by RalfJung** [comment]
Turns out that was just a fluke on my end. I removed that commit.

**Pull request merged**
