### PR TITLE
Refactoring: Couple values and types into an object when passed around together

### PR DESCRIPTION
**Pull request by oli-obk**
This is a pure refactoring and does not touch any logic.

It is a prerequisite for getting rid of our handrolled boilerplate around closure and drop calls.

I also think it makes the "interesting" cases where we fiddle with values' types more explicit.

### CODE REVIEW

**Comment by eddyb** [comment]
Travis failed with:
> The job exceeded the maximum time limit for jobs, and has been terminated.

**Comment by RalfJung** [comment]
I am split-minds about this. It does make things nicer, but I had hoped that we could actually push back on having types everywhere. Right now I think we have types in too many places. For example, I think the memory should not provide all these `read_*` methods -- there should be a single `read` method taking a `MemoryPointer` and a size and alignment and returning a `PrimVal`, and it should read that many bytes -- and if size happens to be the pointer size, it should also handle that case. No more `read_ptr` and `read_uint` and `read_int` and whatnot, not even `read_f{32,64}`. The memory should not even know that types exist.
As next step, `try_read_value` shouldn't need the type -- size and alignment suffice. But maybe the type is still the most convenient way to make that work? I am less offended by `eval_context` knowing about types.

Is this PR making such a change harder or not? If not, it looks good to me. :)

**Comment by RalfJung** [comment]
The changes in the function call hooks certainly look great! So I think I overall like this. It seems to make getting the right type easier for all places where we so far needed types anyway. Doing the memory interface refactoring is still possible from what I can tell.

**Comment by oli-obk** [comment]
I think the memory changes are completely orthogonal. I like the idea of simplifying all the read methods. I'll have a look at that over the weekend

**Comment by RalfJung** [comment]
I have a 3h train ride today, I may just do that. :D

**Pull request merged**
