### PR TITLE
use the new `is_ty_uninhabited_from_all_modules` helper

### PR DESCRIPTION
**Pull request by nikomatsakis**
This is needed as of https://github.com/rust-lang/rust/pull/44501

### CODE REVIEW

**Comment by RalfJung** [comment]
Actually I don't know why miri should even care about inhabitedness. The only [place this is used](https://github.com/solson/miri/blob/728e66473999abf7de5a037158df8e3a7d19be40/src/librustc_mir/interpret/terminator/mod.rs#L254) is another one of these "ad-hoc type validation things" that IMHO we should mostly do away with.

**Comment by oli-obk** [comment]
Fine with me. @nikomatsakis you should disable miri building according to the latest submodule breakage guidelines, since miri has no long lived branch strategy (yet).

We'll merge once it hits nightly and update rustc's miri submodule then.

@RalfJung as long as no tests suddenly pass I'm fine with removing

**Comment by eddyb** [comment]
Oh, @nikomatsakis, I think the problem here is that historical builds might fail if you point the submodule to a commit which might not be guaranteed to end up on master.

**Comment by eddyb** [comment]
Solved by #350.

**Pull request closed without merging**
