### PR TITLE
Simplify dropping by reusing `eval_fn_call`

### PR DESCRIPTION
**Pull request by oli-obk**

### CODE REVIEW

**Comment by eddyb** [comment]
Why do these pull requests have a merge commit in them? IMO they shouldn't.

**Comment by RalfJung** [comment]
LGTM. I never understood that drop code though.^^

**Comment by oli-obk** [comment]
@eddyb that's what happens when I use the Update branch button of github. I can use github's rebase merging strategy which should eliminate the commit. Without using github's features, I'd need to go to a computer every time I want to move a PR along due to another unrelated PR having gotten merged.

**Comment by eddyb** [comment]
Ahhh so it's from other PRs getting merged. Don't mind me then. (I do wish GitHub had web rebase not just merge)

**Comment by RalfJung** [comment]
I actually prefer merge for this purpose. It keeps the commits in the way that the author wrote & tested them. A rebase should require more manual review IMHO.

**Comment by eddyb** [comment]
@RalfJung I meant *specifically* for fixing "merge failures" online.

**Comment by RalfJung** [comment]
But the button that adds merge commits doesn't fix merge failures. It fixes "branch is out of date because stuff has since then been pushed to master". I think merge is the appropriate strategy here.

**Comment by eddyb** [comment]
Wait, "branch is out of date because stuff has since then been pushed to master" is some kind of stricter version of merge failures, that you can opt into? I'm losing track of GitHub features here.
Still, I'd prefer rebases. The reason they're not used is complexity, IMO.

**Comment by RalfJung** [comment]
> Wait, "branch is out of date because stuff has since then been pushed to master" is some kind of stricter version of merge failures, that you can opt into?

Yes, see the screenshot in https://github.com/solson/miri/issues/279#issuecomment-320489747.

**Pull request merged**
