### PR TITLE
WIP rustup

### PR DESCRIPTION
**Pull request by dwrensha**
This at least gets things to typecheck as of `rustc 1.24.0-nightly (b98fd524e 2018-01-05)`. There are still problems.

### CODE REVIEW

**Comment by dwrensha** [comment]
Ugh, I'm getting "no mir for lang_start_internal", I think because https://github.com/rust-lang/rust/commit/81e375dba5e7915548dc6067cf16c62cdbce4853 made that function non-generic.

**Comment by oli-obk** [comment]
The genericness shouldn't matter (due to `-Zalways-encode-mir`. Something else must have changed, too. I'll have a look

**Comment by oli-obk** [comment]
Ok so it magically works with my miri PR... Some other things are still failing though, but I have a fairly good idea what's the problem.

**Comment by oli-obk** [comment]
Thanks! I'm tracking your commits in the `rustup` branch

**Pull request closed without merging**
