### PR TITLE
Implement `align_offset` intrinsic and thus enabling `from_utf8`

### LINKED ISSUE #190: ReadPointerAsBytes error in ::std::str::from_utf8()
```rust
// test.rs

fn main() {
    let _ = ::std::str::from_utf8(b"a");
}
```

```
$ cargo run --bin miri -- --sysroot ~/.xargo/HOST test.rs
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
     Running `target/debug/miri --sysroot /home/dwrensha/.xargo/HOST test.rs`
WARN:miri::terminator: ignoring C ABI call: pthread_attr_init
WARN:miri::terminator: ignoring C ABI call: pthread_self
WARN:miri::terminator: ignoring C ABI call: pthread_getattr_np
WARN:miri::terminator: ignoring C ABI call: pthread_attr_getstack
WARN:miri::terminator: ignoring C ABI call: pthread_attr_destroy
WARN:miri::terminator: ignoring C ABI call: pthread_mutex_lock
WARN:miri::terminator: ignoring C ABI call: pthread_mutex_unlock
WARN:miri::terminator: ignoring C ABI call: pthread_mutexattr_init
WARN:miri::terminator: ignoring C ABI call: pthread_mutexattr_settype
WARN:miri::terminator: ignoring C ABI call: pthread_mutex_init
WARN:miri::terminator: ignoring C ABI call: pthread_mutexattr_destroy
WARN:miri::terminator: ignoring C ABI call: pthread_condattr_init
WARN:miri::terminator: ignoring C ABI call: pthread_condattr_setclock
WARN:miri::terminator: ignoring C ABI call: pthread_cond_init
WARN:miri::terminator: ignoring C ABI call: pthread_condattr_destroy
WARN:miri::terminator: ignoring C ABI call: pthread_mutex_lock
WARN:miri::terminator: ignoring C ABI call: pthread_mutex_unlock
error: a raw memory access tried to access part of a pointer value as raw bytes
     |
note: inside call to core::str::run_utf8_validation
note: inside call to std::str::from_utf8
    --> test.rs:4:13
     |
4    |     let _ = ::std::str::from_utf8(b"a");
     |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
note: inside call to main
note: inside call to <fn() as std::ops::FnOnce<()>>::call_once - shim(fn())
note: inside call to std::panicking::try::do_call::<fn(), ()>
note: inside call to std::panicking::try::<(), fn()>
note: inside call to std::panic::catch_unwind::<fn(), ()>
note: inside call to std::rt::lang_start

error: aborting due to previous error(s)

thread 'main' panicked at 'Box<Any>', /checkout/src/librustc_errors/lib.rs:514
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

### PR DESCRIPTION
**Pull request by oli-obk**
fixes #190

### CODE REVIEW

**Comment by KodrAus** [comment]
So I guess we'll need to do a pass through `std` and replace any other instances of manual alignment checking with this new intrinsic (or one of the fns on top of it once that lands) so `miri` can make the most of it?

**Comment by oli-obk** [comment]
> So I guess we'll need to do a pass through std and replace any other instances of manual alignment checking with this new intrinsic (or one of the fns on top of it once that lands) so miri can make the most of it?

Yes. I'll be rerunning miri on the rust test suite to figure out which places are relevant.

For now this PR is blocked on @eddyb's fix for promoteds inside statics.

**Comment by RalfJung** [comment]
> @eddyb's fix for promoteds inside statics.

Yeah, master is currently red. Got a link for that?

**Comment by oli-obk** [comment]
Nope. No PR open yet. Discussion is [here](https://botbot.me/mozilla/rust-internals/2017-08-31/?msg=90511143&page=3)

**Comment by eddyb** [comment]
rust-lang/rust#44252 merged, next nightly should be fixed.

**Comment by RalfJung** [comment]
It's not great that we will never execute the "aligned" loop of code using this -- if there's bad things going on there, miri will not notice. But I guess there's not too much we can do.

**Comment by oli-obk** [comment]
We can improve the intrinsic to work if the alignment of the allocation is bigger than 1.

Then we can allocate some bytes but with a high alignment and run the utf8 checks on that memory

**Comment by RalfJung** [comment]
Yeah that would help for this, but not in general for other uses of the intrinsic.

**Comment by oli-obk** [comment]
Right. For that we'll need the intptrcast model

**Pull request merged**
