### PR TITLE
Read discriminant as a signed integer.

### LINKED ISSUE #78: reading invalid discriminant in derived `PartialOrd` impl
repro:

```rust
#[derive(PartialEq,PartialOrd,Eq,Ord)]
struct ShortCircuit {
    x: isize,
}

pub fn main() {
    let a = ShortCircuit { x: 1 };
    let b = ShortCircuit { x: 2 };

    a.cmp(&b);
}
```

### PR DESCRIPTION
**Pull request by plietar**
This ensures it gets sign extended correctly.

Fixes #78

### CODE REVIEW

**Comment by eddyb** [comment]
There's an `is_sized` field in `CEnum` which *needs* to be used here, and `General` is *always* unsigned.

Unsigned is far more common and assuming signed would break enums with more than 128 variants, for starters.

**Comment by oli-obk** [comment]
Also, this does not fix #78, but a different issue as far as I can see

**Comment by plietar** [comment]
@eddyb 
right thanks, I had overlooked this. Should be correct now.

@oli-obk 
Are you sure ? The snippet in #78  works with this PR.
The error was caused by a match on `Ordering::Less`, which has discriminant -1.

**Comment by oli-obk** [comment]
Ah, cool, that makes sense

**Pull request merged**
