### PR TITLE
Use the core miri from rustc

### PR DESCRIPTION
**Pull request by oli-obk**
see https://github.com/rust-lang/rust/pull/45002 for what's going on

### CODE REVIEW

**Comment by RalfJung** [comment]
With this merged, what will the development process of miri look like? To the best of my knowledge, miri needs a stage 2 compiler, so testing any change in the part living in librustc_mir requires waiting ~20min for the stage 2 rebuild to complete?

**Comment by oli-obk** [comment]
> To the best of my knowledge, miri needs a stage 2 compiler, so testing any change in the part living in librustc_mir requires waiting ~20min for the stage 2 rebuild to complete?

It's slightly worse **and** slightly better than that:

the bad: miri core lives in `librustc`, which takes quite a while to compile
the good: we don't need much in order to get miri to compile, so it'll run on a stage 1

> With this merged, what will the development process of miri look like?

0. change `codegen-units = 0` in `config.toml`
1. Make changes in `librustc`
2. run `./x.py test --incremental src/tools/miri`
3. wait around 5 min

Note that I plan to move *loads* of stuff from `librustc` to `librustc_mir`, which should speed up the common dev cycle by a lot.

**Comment by RalfJung** [comment]
That's great!

Last time I tried, using a stage 1 to compile miri did not work because then librustc and libstd are not compiled with the same compiler (or [something like that](https://github.com/solson/miri/issues/293#issuecomment-321341325)...).

> change codegen-units = 0 in config.toml

Why this?

**Comment by oli-obk** [comment]
> Why this?

~half the build time

**Comment by oli-obk** [comment]
Hmm... I appear to have misunderstood what's going on...

**building** miri is fast.

**testing** miri does require the appropriate libstd and gives the error you described.

I just never noticed because I was just trying to get miri to build, not test it...

Still, it should be possible to just recompile libstd instead of the entire compiler. I'll investigate

**Comment by RalfJung** [comment]
Did you deliberately delete Cargo.lock in the last commit?

**Comment by oli-obk** [comment]
Yes. We're reusing the one from rustc

**Comment by RalfJung** [comment]
I am confused. This repository ultimately contains a binary that's essentially a small wrapper around the machinery in librustc, right? It however still my add some additional dependencies, like `byteorder`. Where are these locked?

**Comment by oli-obk** [comment]
These are also in the rustc lock file. For now both are closely coupled.

**Comment by RalfJung** [comment]
If Cargo.lock is not in the repository, at least it should be in `.gitignore` to keep`git status` happy.

**Comment by oli-obk** [comment]
Agreed

**Comment by RalfJung** [comment]
Something is wrong with the miri in this PR.  I compiled it against [this branch](https://github.com/oli-obk/rust/tree/miri) (specifically, against 2a80d781f5) and then ran `cargo run --bin miri tests/run-pass/bools.rs`. I expected this to succeed with no output. Instead, this command prints the output reproduced below and creates a binary called `bools` in the current directory. Looks like the code that makes rustc *only* do the MIR evaluation and not produce any output broke?
```
INFO:rustc_metadata::creader: resolving crate `extern crate std as std`
INFO:rustc_metadata::creader: falling back to a load
INFO:rustc_metadata::locator: lib candidate: /home/r/.rustup/toolchains/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-a8de6a4298d01367.rlib
INFO:rustc_metadata::locator: lib candidate: /home/r/.rustup/toolchains/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd_unicode-c87147d9878a34a6.rlib
INFO:rustc_metadata::locator: lib candidate: /home/r/.rustup/toolchains/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-a8de6a4298d01367.so
INFO:rustc_metadata::locator: rlib reading metadata from: /home/r/src/rust/rustc/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-a8de6a4298d01367.rlib
INFO:rustc_metadata::locator: reading "libstd-a8de6a4298d01367.rlib" => Duration { secs: 0, nanos: 2814246 }
INFO:rustc_metadata::locator: rlib reading metadata from: /home/r/src/rust/rustc/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd_unicode-c87147d9878a34a6.rlib
INFO:rustc_metadata::locator: reading "libstd_unicode-c87147d9878a34a6.rlib" => Duration { secs: 0, nanos: 1129021 }
INFO:rustc_metadata::locator: Rejecting via crate name
INFO:rustc_metadata::locator: metadata mismatch
INFO:rustc_metadata::creader: register crate `extern crate std as std`
INFO:rustc_metadata::creader: resolving crate `extern crate core as core`
INFO:rustc_metadata::creader: falling back to a load
INFO:rustc_metadata::locator: lib candidate: /home/r/.rustup/toolchains/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-f61c023fb8fcfea8.rlib
INFO:rustc_metadata::locator: rlib reading metadata from: /home/r/src/rust/rustc/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-f61c023fb8fcfea8.rlib
INFO:rustc_metadata::locator: reading "libcore-f61c023fb8fcfea8.rlib" => Duration { secs: 0, nanos: 1357694 }
INFO:rustc_metadata::creader: register crate `extern crate core as core`
INFO:rustc_metadata::creader: resolving crate `extern crate alloc as alloc`
INFO:rustc_metadata::creader: falling back to a load
INFO:rustc_metadata::locator: lib candidate: /home/r/.rustup/toolchains/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-bad119b0f880de53.rlib
INFO:rustc_metadata::locator: lib candidate: /home/r/.rustup/toolchains/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc_jemalloc-47b26bd121b72d91.rlib
INFO:rustc_metadata::locator: lib candidate: /home/r/.rustup/toolchains/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc_system-9ff2c67f40fe5858.rlib
INFO:rustc_metadata::locator: rlib reading metadata from: /home/r/src/rust/rustc/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-bad119b0f880de53.rlib
INFO:rustc_metadata::locator: reading "liballoc-bad119b0f880de53.rlib" => Duration { secs: 0, nanos: 1746982 }
INFO:rustc_metadata::locator: rlib reading metadata from: /home/r/src/rust/rustc/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc_system-9ff2c67f40fe5858.rlib
INFO:rustc_metadata::locator: reading "liballoc_system-9ff2c67f40fe5858.rlib" => Duration { secs: 0, nanos: 869297 }
INFO:rustc_metadata::locator: Rejecting via crate name
INFO:rustc_metadata::locator: metadata mismatch
INFO:rustc_metadata::locator: rlib reading metadata from: /home/r/src/rust/rustc/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc_jemalloc-47b26bd121b72d91.rlib
INFO:rustc_metadata::locator: reading "liballoc_jemalloc-47b26bd121b72d91.rlib" => Duration { secs: 0, nanos: 26494300 }
INFO:rustc_metadata::locator: Rejecting via crate name
INFO:rustc_metadata::locator: metadata mismatch
INFO:rustc_metadata::creader: register crate `extern crate alloc as alloc`
INFO:rustc_metadata::creader: resolving crate `extern crate core as core`
INFO:rustc_metadata::creader: resolving crate `extern crate std_unicode as std_unicode`
INFO:rustc_metadata::creader: falling back to a load
INFO:rustc_metadata::locator: lib candidate: /home/r/.rustup/toolchains/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd_unicode-c87147d9878a34a6.rlib
INFO:rustc_metadata::locator: rlib reading metadata from: /home/r/src/rust/rustc/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd_unicode-c87147d9878a34a6.rlib
INFO:rustc_metadata::locator: reading "libstd_unicode-c87147d9878a34a6.rlib" => Duration { secs: 0, nanos: 32482 }
INFO:rustc_metadata::creader: register crate `extern crate std_unicode as std_unicode`
INFO:rustc_metadata::creader: resolving crate `extern crate core as core`
INFO:rustc_metadata::creader: resolving crate `extern crate std_unicode as std_unicode`
INFO:rustc_metadata::creader: resolving crate `extern crate alloc_system as alloc_system`
INFO:rustc_metadata::creader: falling back to a load
INFO:rustc_metadata::locator: lib candidate: /home/r/.rustup/toolchains/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc_system-9ff2c67f40fe5858.rlib
INFO:rustc_metadata::locator: rlib reading metadata from: /home/r/src/rust/rustc/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc_system-9ff2c67f40fe5858.rlib
INFO:rustc_metadata::locator: reading "liballoc_system-9ff2c67f40fe5858.rlib" => Duration { secs: 0, nanos: 18683 }
INFO:rustc_metadata::creader: register crate `extern crate alloc_system as alloc_system`
INFO:rustc_metadata::creader: resolving crate `extern crate core as core`
INFO:rustc_metadata::creader: resolving crate `extern crate alloc as alloc`
INFO:rustc_metadata::creader: resolving crate `extern crate std_unicode as std_unicode`
INFO:rustc_metadata::creader: resolving crate `extern crate libc as libc`
INFO:rustc_metadata::creader: falling back to a load
INFO:rustc_metadata::locator: lib candidate: /home/r/.rustup/toolchains/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-62e92838462af3c2.rlib
INFO:rustc_metadata::locator: lib candidate: /home/r/.rustup/toolchains/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-e1c7eeeb00260d82.rlib
INFO:rustc_metadata::locator: rlib reading metadata from: /home/r/src/rust/rustc/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-62e92838462af3c2.rlib
INFO:rustc_metadata::locator: reading "liblibc-62e92838462af3c2.rlib" => Duration { secs: 0, nanos: 1523015 }
INFO:rustc_metadata::locator: Rejecting via hash: expected 53c340c60f49075b got 95c7175425bc5fde
INFO:rustc_metadata::locator: metadata mismatch
INFO:rustc_metadata::locator: rlib reading metadata from: /home/r/src/rust/rustc/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-e1c7eeeb00260d82.rlib
INFO:rustc_metadata::locator: reading "liblibc-e1c7eeeb00260d82.rlib" => Duration { secs: 0, nanos: 1580605 }
INFO:rustc_metadata::creader: register crate `extern crate libc as libc`
INFO:rustc_metadata::creader: resolving crate `extern crate core as core`
INFO:rustc_metadata::creader: resolving crate `extern crate libc as libc`
INFO:rustc_metadata::creader: resolving crate `extern crate unwind as unwind`
INFO:rustc_metadata::creader: falling back to a load
INFO:rustc_metadata::locator: lib candidate: /home/r/.rustup/toolchains/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunwind-3830ae5679a0b739.rlib
INFO:rustc_metadata::locator: rlib reading metadata from: /home/r/src/rust/rustc/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunwind-3830ae5679a0b739.rlib
INFO:rustc_metadata::locator: reading "libunwind-3830ae5679a0b739.rlib" => Duration { secs: 0, nanos: 1206061 }
INFO:rustc_metadata::creader: register crate `extern crate unwind as unwind`
INFO:rustc_metadata::creader: resolving crate `extern crate core as core`
INFO:rustc_metadata::creader: resolving crate `extern crate libc as libc`
INFO:rustc_metadata::creader: resolving crate `extern crate compiler_builtins as compiler_builtins`
INFO:rustc_metadata::creader: falling back to a load
INFO:rustc_metadata::locator: lib candidate: /home/r/.rustup/toolchains/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-3b206b25583c2149.rlib
INFO:rustc_metadata::locator: rlib reading metadata from: /home/r/src/rust/rustc/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-3b206b25583c2149.rlib
INFO:rustc_metadata::locator: reading "libcompiler_builtins-3b206b25583c2149.rlib" => Duration { secs: 0, nanos: 3942438 }
INFO:rustc_metadata::creader: register crate `extern crate compiler_builtins as compiler_builtins`
INFO:rustc_metadata::creader: resolving crate `extern crate core as core`
INFO:rustc_metadata::creader: resolving crate `extern crate alloc_jemalloc as alloc_jemalloc`
INFO:rustc_metadata::creader: falling back to a load
INFO:rustc_metadata::locator: lib candidate: /home/r/.rustup/toolchains/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc_jemalloc-47b26bd121b72d91.rlib
INFO:rustc_metadata::locator: rlib reading metadata from: /home/r/src/rust/rustc/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc_jemalloc-47b26bd121b72d91.rlib
INFO:rustc_metadata::locator: reading "liballoc_jemalloc-47b26bd121b72d91.rlib" => Duration { secs: 0, nanos: 210027 }
INFO:rustc_metadata::creader: register crate `extern crate alloc_jemalloc as alloc_jemalloc`
INFO:rustc_metadata::creader: resolving crate `extern crate core as core`
INFO:rustc_metadata::creader: resolving crate `extern crate alloc as alloc`
INFO:rustc_metadata::creader: resolving crate `extern crate std_unicode as std_unicode`
INFO:rustc_metadata::creader: resolving crate `extern crate alloc_system as alloc_system`
INFO:rustc_metadata::creader: resolving crate `extern crate libc as libc`
INFO:rustc_metadata::creader: resolving crate `extern crate panic_unwind as panic_unwind`
INFO:rustc_metadata::creader: falling back to a load
INFO:rustc_metadata::locator: lib candidate: /home/r/.rustup/toolchains/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib/libpanic_unwind-5bef2c52ac19d279.rlib
INFO:rustc_metadata::locator: rlib reading metadata from: /home/r/src/rust/rustc/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib/libpanic_unwind-5bef2c52ac19d279.rlib
INFO:rustc_metadata::locator: reading "libpanic_unwind-5bef2c52ac19d279.rlib" => Duration { secs: 0, nanos: 851399 }
INFO:rustc_metadata::creader: register crate `extern crate panic_unwind as panic_unwind`
INFO:rustc_metadata::creader: resolving crate `extern crate core as core`
INFO:rustc_metadata::creader: resolving crate `extern crate alloc as alloc`
INFO:rustc_metadata::creader: resolving crate `extern crate std_unicode as std_unicode`
INFO:rustc_metadata::creader: resolving crate `extern crate libc as libc`
INFO:rustc_metadata::creader: resolving crate `extern crate unwind as unwind`
INFO:rustc_metadata::creader: resolving crate `extern crate alloc_jemalloc as alloc_jemalloc`
INFO:rustc_metadata::creader: injecting a dep from 1 to 10
INFO:rustc_metadata::creader: panic runtime not found -- loading panic_unwind
INFO:rustc_metadata::creader: resolving crate `extern crate panic_unwind as panic_unwind`
INFO:rustc_metadata::creader: injecting a dep from 1 to 10
INFO:rustc_metadata::creader: resolved crates:
INFO:rustc_metadata::creader:   name: compiler_builtins
INFO:rustc_metadata::creader:   cnum: 8
INFO:rustc_metadata::creader:   hash: b73d11f850d91ffd
INFO:rustc_metadata::creader:   reqd: Explicit
INFO:rustc_metadata::creader:    rlib: /home/r/src/rust/rustc/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-3b206b25583c2149.rlib
INFO:rustc_metadata::creader:   name: alloc_system
INFO:rustc_metadata::creader:   cnum: 5
INFO:rustc_metadata::creader:   hash: 3591d5434fe36065
INFO:rustc_metadata::creader:   reqd: Explicit
INFO:rustc_metadata::creader:    rlib: /home/r/src/rust/rustc/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc_system-9ff2c67f40fe5858.rlib
INFO:rustc_metadata::creader:   name: core
INFO:rustc_metadata::creader:   cnum: 2
INFO:rustc_metadata::creader:   hash: d276487879ad6e45
INFO:rustc_metadata::creader:   reqd: Explicit
INFO:rustc_metadata::creader:    rlib: /home/r/src/rust/rustc/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-f61c023fb8fcfea8.rlib
INFO:rustc_metadata::creader:   name: panic_unwind
INFO:rustc_metadata::creader:   cnum: 10
INFO:rustc_metadata::creader:   hash: dd39b5a6a2947611
INFO:rustc_metadata::creader:   reqd: Implicit
INFO:rustc_metadata::creader:    rlib: /home/r/src/rust/rustc/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib/libpanic_unwind-5bef2c52ac19d279.rlib
INFO:rustc_metadata::creader:   name: unwind
INFO:rustc_metadata::creader:   cnum: 7
INFO:rustc_metadata::creader:   hash: 5dda5ce092989713
INFO:rustc_metadata::creader:   reqd: Explicit
INFO:rustc_metadata::creader:    rlib: /home/r/src/rust/rustc/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunwind-3830ae5679a0b739.rlib
INFO:rustc_metadata::creader:   name: std_unicode
INFO:rustc_metadata::creader:   cnum: 4
INFO:rustc_metadata::creader:   hash: 50b2f8948a11684a
INFO:rustc_metadata::creader:   reqd: Explicit
INFO:rustc_metadata::creader:    rlib: /home/r/src/rust/rustc/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd_unicode-c87147d9878a34a6.rlib
INFO:rustc_metadata::creader:   name: std
INFO:rustc_metadata::creader:   cnum: 1
INFO:rustc_metadata::creader:   hash: cdb2efc777c2032d
INFO:rustc_metadata::creader:   reqd: Explicit
INFO:rustc_metadata::creader:   dylib: /home/r/src/rust/rustc/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-a8de6a4298d01367.so
INFO:rustc_metadata::creader:    rlib: /home/r/src/rust/rustc/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-a8de6a4298d01367.rlib
INFO:rustc_metadata::creader:   name: alloc_jemalloc
INFO:rustc_metadata::creader:   cnum: 9
INFO:rustc_metadata::creader:   hash: 00ced9e93c7f5cdf
INFO:rustc_metadata::creader:   reqd: Implicit
INFO:rustc_metadata::creader:    rlib: /home/r/src/rust/rustc/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc_jemalloc-47b26bd121b72d91.rlib
INFO:rustc_metadata::creader:   name: libc
INFO:rustc_metadata::creader:   cnum: 6
INFO:rustc_metadata::creader:   hash: 53c340c60f49075b
INFO:rustc_metadata::creader:   reqd: Explicit
INFO:rustc_metadata::creader:    rlib: /home/r/src/rust/rustc/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-e1c7eeeb00260d82.rlib
INFO:rustc_metadata::creader:   name: alloc
INFO:rustc_metadata::creader:   cnum: 3
INFO:rustc_metadata::creader:   hash: 3537426071db9844
INFO:rustc_metadata::creader:   reqd: Explicit
INFO:rustc_metadata::creader:    rlib: /home/r/src/rust/rustc/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-bad119b0f880de53.rlib
Pre-trans
Ty interner             total           ty region  both
    TyAdt             :    730 48.9%,  0.0%   0.0%  0.0%
    TyArray           :    174 11.7%,  0.0%   0.0%  0.0%
    TySlice           :     17  1.1%,  0.0%   0.0%  0.0%
    TyRawPtr          :      6  0.4%,  0.0%   0.0%  0.0%
    TyRef             :    232 15.5%,  0.1%   0.0%  0.0%
    TyFnDef           :     34  2.3%,  0.1%   0.0%  0.0%
    TyFnPtr           :     93  6.2%,  0.0%   0.0%  0.0%
    TyGenerator       :      0  0.0%,  0.0%   0.0%  0.0%
    TyForeign         :      0  0.0%,  0.0%   0.0%  0.0%
    TyDynamic         :      2  0.1%,  0.0%   0.0%  0.0%
    TyClosure         :      0  0.0%,  0.0%   0.0%  0.0%
    TyTuple           :     42  2.8%,  0.1%   0.0%  0.0%
    TyParam           :    148  9.9%,  0.0%   0.0%  0.0%
    TyInfer           :     13  0.9%,  0.9%   0.0%  0.0%
    TyProjection      :      2  0.1%,  0.0%   0.0%  0.0%
    TyAnon            :      0  0.0%,  0.0%   0.0%  0.0%
                  total   1493         1.2%   0.0%  0.0%
Substs interner: #530
Region interner: #614
Stability interner: #0
Interpret interner: #6
Layout interner: #5
INFO:rustc_trans_utils::link: LinkMeta { crate_hash: Svh { hash: 17437669911095309509 } }
INFO:rustc::traits::trans: Cache miss: Binder(<&i64 as std::fmt::Debug>) => VtableImpl(impl_def_id=DefId { krate: CrateNum(2), index: DefIndex(0:18269) => core[1c3d]::fmt[0]::{{impl}}[46] }, substs=Slice([ReErased, i64]), nested=[()])
INFO:rustc::traits::trans: Cache miss: Binder(<&i16 as std::fmt::Debug>) => VtableImpl(impl_def_id=DefId { krate: CrateNum(2), index: DefIndex(0:18269) => core[1c3d]::fmt[0]::{{impl}}[46] }, substs=Slice([ReErased, i16]), nested=[()])
INFO:rustc::traits::trans: Cache miss: Binder(<&str as std::any::Any>) => VtableImpl(impl_def_id=DefId { krate: CrateNum(2), index: DefIndex(0:1282) => core[1c3d]::any[0]::{{impl}}[0] }, substs=Slice([&str]), nested=[()])
INFO:rustc::traits::trans: Cache miss: Binder(<std::heap::Heap as std::heap::Alloc>) => VtableImpl(impl_def_id=DefId { krate: CrateNum(3), index: DefIndex(0:69) => alloc[60f8]::heap[0]::{{impl}}[0] }, substs=Slice([]), nested=[])
INFO:rustc::traits::trans: Cache miss: Binder(<std::mem::ManuallyDrop<std::heap::AllocErr> as std::ops::DerefMut>) => VtableImpl(impl_def_id=DefId { krate: CrateNum(2), index: DefIndex(0:645) => core[1c3d]::mem[0]::{{impl}}[8] }, substs=Slice([std::heap::AllocErr]), nested=[()])
INFO:rustc::traits::trans: Cache miss: Binder(<[closure@DefId { krate: CrateNum(3), index: DefIndex(1:34) => alloc[60f8]::heap[0]::exchange_malloc[0]::{{closure}}[0] }] as std::ops::FnOnce<(std::heap::AllocErr,)>>) => VtableClosure(closure_def_id=DefId { krate: CrateNum(3), index: DefIndex(1:34) => alloc[60f8]::heap[0]::exchange_malloc[0]::{{closure}}[0] }, substs=ClosureSubsts { substs: Slice([]) }, nested=[()])
INFO:rustc::traits::trans: Cache miss: Binder(<i64 as std::fmt::Debug>) => VtableImpl(impl_def_id=DefId { krate: CrateNum(2), index: DefIndex(0:18158) => core[1c3d]::fmt[0]::num[0]::{{impl}}[71] }, substs=Slice([]), nested=[])
INFO:rustc::traits::trans: Cache miss: Binder(<i16 as std::fmt::Debug>) => VtableImpl(impl_def_id=DefId { krate: CrateNum(2), index: DefIndex(0:18118) => core[1c3d]::fmt[0]::num[0]::{{impl}}[51] }, substs=Slice([]), nested=[])
INFO:rustc_trans::base: trans_instance(boolean)
INFO:rustc_trans::base: trans_instance(if_false)
INFO:rustc_trans::base: trans_instance(if_true)
INFO:rustc_trans::base: trans_instance(match_bool)
INFO:rustc_trans::base: trans_instance(main)
INFO:rustc_trans::base: trans_instance(std::fmt::ArgumentV1::new::<&i64>)
INFO:rustc_trans::base: trans_instance(std::fmt::ArgumentV1::new::<&i16>)
INFO:rustc_trans::base: trans_instance(std::fmt::Arguments::new_v1_formatted)
INFO:rustc_trans::base: trans_instance(<&'a T as std::fmt::Debug><i16>::fmt)
INFO:rustc_trans::base: trans_instance(<&'a T as std::fmt::Debug><i64>::fmt)
INFO:rustc_trans::base: trans_instance(alloc::heap::exchange_malloc)
INFO:rustc_trans::base: trans_instance(alloc::heap::exchange_malloc::{{closure}})
INFO:rustc_trans::base: trans_instance(<std::heap::Heap as std::heap::Alloc>::oom)
INFO:rustc_trans::base: trans_instance(<std::heap::Heap as std::heap::Alloc>::alloc)
INFO:rustc_trans::base: trans_instance(<std::mem::ManuallyDrop<T>><std::heap::AllocErr>::into_inner)
INFO:rustc_trans::base: trans_instance(<std::mem::ManuallyDrop<T>><std::heap::AllocErr>::new)
INFO:rustc_trans::base: trans_instance(std::mem::uninitialized::<std::heap::AllocErr>)
INFO:rustc_trans::base: trans_instance(<std::mem::ManuallyDrop<T> as std::ops::DerefMut><std::heap::AllocErr>::deref_mut)
INFO:rustc_trans::base: trans_instance(std::heap::Layout::from_size_align_unchecked)
INFO:rustc_trans::base: trans_instance(std::heap::Layout::size)
INFO:rustc_trans::base: trans_instance(std::heap::Layout::align)
INFO:rustc_trans::base: trans_instance(<T as std::any::Any><&str>::get_type_id)
INFO:rustc_trans::base: trans_instance(std::any::TypeId::of::<&str>)
INFO:rustc_trans::base: trans_instance(<std::boxed::Box<T>><&str>::new)
INFO:rustc_trans::base: trans_instance(std::rt::begin_panic::<&str>)
INFO:rustc_trans::base: trans_instance(std::ptr::<impl *mut T><u8>::is_null)
INFO:rustc_trans::base: trans_instance(std::ptr::null_mut::<u8>)
INFO:rustc_trans::base: trans_instance(<std::result::Result<T, E>><*mut u8, std::heap::AllocErr>::unwrap_or_else::<[closure@DefId { krate: CrateNum(3), index: DefIndex(1:34) => alloc[60f8]::heap[0]::exchange_malloc[0]::{{closure}}[0] }]>)
INFO:rustc_trans::base: trans_instance(std::ptr::drop_in_place::<&str> - shim(None))
Post-trans
Ty interner             total           ty region  both
    TyAdt             :   1124 20.3%,  0.0%   0.0%  0.0%
    TyArray           :    199  3.6%,  0.0%   0.0%  0.0%
    TySlice           :     25  0.5%,  0.0%   0.0%  0.0%
    TyRawPtr          :     26  0.5%,  0.0%   0.0%  0.0%
    TyRef             :   1530 27.7%,  0.0%   0.0%  0.0%
    TyFnDef           :   2190 39.6%,  0.0%   0.0%  0.0%
    TyFnPtr           :    132  2.4%,  0.0%   0.0%  0.0%
    TyGenerator       :      0  0.0%,  0.0%   0.0%  0.0%
    TyForeign         :      0  0.0%,  0.0%   0.0%  0.0%
    TyDynamic         :     28  0.5%,  0.0%   0.0%  0.0%
    TyClosure         :      1  0.0%,  0.0%   0.0%  0.0%
    TyTuple           :     93  1.7%,  0.0%   0.0%  0.0%
    TyParam           :    150  2.7%,  0.0%   0.0%  0.0%
    TyInfer           :     13  0.2%,  0.2%   0.0%  0.0%
    TyProjection      :     13  0.2%,  0.0%   0.0%  0.0%
    TyAnon            :      0  0.0%,  0.0%   0.0%  0.0%
                  total   5524         0.3%   0.0%  0.0%
Substs interner: #1759
Region interner: #746
Stability interner: #0
Interpret interner: #15
Layout interner: #53
INFO:rustc_trans::back::link: preparing CrateTypeExecutable to "bools"
INFO:rustc_trans::back::link: "cc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-m64" "-L" "/home/r/.rustup/toolchains/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib" "bools.bools0.rcgu.o" "bools.bools1.rcgu.o" "bools.bools2.rcgu.o" "bools.bools3.rcgu.o" "bools.bools4.rcgu.o" "bools.bools5.rcgu.o" "bools.bools6.rcgu.o" "bools.bools7.rcgu.o" "bools.bools8.rcgu.o" "bools.bools9.rcgu.o" "-o" "bools" "bools.crate.allocator.rcgu.o" "-Wl,--gc-sections" "-pie" "-Wl,-z,relro,-z,now" "-nodefaultlibs" "-L" "/home/r/.rustup/toolchains/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "/home/r/src/rust/rustc/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-a8de6a4298d01367.rlib" "/home/r/src/rust/rustc/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc_jemalloc-47b26bd121b72d91.rlib" "/home/r/src/rust/rustc/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib/libpanic_unwind-5bef2c52ac19d279.rlib" "/home/r/src/rust/rustc/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunwind-3830ae5679a0b739.rlib" "/home/r/src/rust/rustc/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc_system-9ff2c67f40fe5858.rlib" "/home/r/src/rust/rustc/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-e1c7eeeb00260d82.rlib" "/home/r/src/rust/rustc/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-bad119b0f880de53.rlib" "/home/r/src/rust/rustc/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd_unicode-c87147d9878a34a6.rlib" "/home/r/src/rust/rustc/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-f61c023fb8fcfea8.rlib" "/home/r/src/rust/rustc/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-3b206b25583c2149.rlib" "-Wl,-Bdynamic" "-l" "dl" "-l" "rt" "-l" "pthread" "-l" "pthread" "-l" "gcc_s" "-l" "c" "-l" "m" "-l" "rt" "-l" "pthread" "-l" "util" "-l" "util"
INFO:rustc_trans::back::link: linker stderr:

INFO:rustc_trans::back::link: linker stdout:

```

**Pull request merged**
