### PR TITLE
Removed transmute from intrinsic.rs

### PR DESCRIPTION
**Pull request by TheDarkula**
r? @RalfJung

### CODE REVIEW

**Comment by RalfJung** [comment]
That looks exactly right, thanks! However, it seems you worked on an older version of `master`; GitHub says there are merge conflicts. (And nothing has landed in the last 1h so these conflicts were present already when you opened the PR.)

Can you resolve those conflicts?

**Comment by RalfJung** [comment]
Thanks!

Now we just have to wait for a nightly to happen.

**Comment by TheDarkula** [comment]
Ah. I was wondering why the builds were still failing :)

**Comment by RalfJung** [comment]
Now that we got a nightly, please update the `rust-toolchain` file to `nightly-2018-08-32`. Then CI should become green.

**Comment by RalfJung** [comment]
Eh, sorry, I had a typo there. There was no nightly on August 32snd.^^

Let me land the other PR first to make CI green again...

**Comment by RalfJung** [comment]
I resolved that conflict for you.

**Pull request merged**
