### PR TITLE
test that we support partial invalidation of mutable references

### PR DESCRIPTION
**Pull request by RalfJung**

### CODE REVIEW

**Comment by RalfJung** [comment]
Thanks to @Gankro for the testcase!

**Comment by Gankro** [comment]
context: this demonstrates that the stack model is *not* equivalent to (and in fact more powerful than)  creating a tree of borrows rooted at each allocation. In particular, it's possible for a borrow to be popped off of one byte's stack, but not another. This wouldn't be supported if the borrow was "fused" into a single node in a borrow-tree.

**Comment by Gankro** [comment]
(you could maybe fix this by splitting the node when you want to do a partial pop but, messy)

**Comment by RalfJung** [comment]
There's a variant of that tree though (which I considered for some time), where a location has a pointer into the tree to remember which part of it may still be used. There, the 2nd location could update its pointer to only allow `data` and its parents in the tree, while the 1st location still permits `shard`.

I think such a tree-based model can be made at least very close to the stacks, but ultimately found it much simpler to have everything per-location than having a per-location pointer-to-tree and a global tree.

**Comment by Gankro** [comment]
I meant that you could try to salvage this idea of a "tree of borrows" by being able to split borrow nodes when they become partially invalidated, but at that point you're just making a more complicated (but potentially more compact?) stack model.

**Comment by RalfJung** [comment]
"compact" maybe in terms of the "shadow data structure" being added, but I think it'd get *less* compact in terms of how complex the rules are.

**Comment by Gankro** [comment]
Yes I was thinking in terms of the footprint of the UB checker.

**Pull request merged**
