### PR TITLE
fix issue 184 by forcing transmute's argument to have an allocation

### LINKED ISSUE #184: u64 -> [u8; 8] transmute triggers spurious alignment error
```rust
// test.rs

pub fn main() {
    let bytes: [u8; 8] = unsafe { ::std::mem::transmute(0u64) };
    let _: &[u8] = &bytes;
}
```

```
$ cargo run --bin miri -- test.rs
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
     Running `target/debug/miri test.rs`
error: tried to access memory with alignment 1, but alignment 8 is required
 --> test.rs:5:20
  |
5 |     let _: &[u8] = &bytes;
  |                    ^^^^^^
  |
note: inside call to main
 --> test.rs:3:1
  |
3 | / pub fn main() {
4 | |     let bytes: [u8; 8] = unsafe { ::std::mem::transmute(0u64) };
5 | |     let _: &[u8] = &bytes;
6 | | }
  | |_^

error: aborting due to previous error(s)
```

### PR DESCRIPTION
**Pull request by dwrensha**
Fixes #184.

### CODE REVIEW

**Comment by dwrensha** [comment]
@oli-obk: do we also need to do something with `mark_packed()`, as you had mentioned?

**Comment by eddyb** [comment]
I don't agree with this approach - it's wrong for packed structs AFAICT - you want `write_value` to take an alignment or something similar. See `librustc_trans` for how `LvalueRef` handles alignment there.

**Comment by oli-obk** [comment]
Yea. I think that it would be correct to treat the destination as a packed struct. So if the destination's alignment is smaller than the source's, force_allocate and mark_packed the destination. Then the code should work as it is.

The current code allows later writes and reads with large alignments even though it shouldn't

**Comment by oli-obk** [comment]
@eddyb: I chose the mark_packed approach over passing alignments, because that would have infected everything

**Comment by eddyb** [comment]
But creating allocations is incorrect for packed structs because allocations are untyped.
So you *really* have to deduce required alignment from MIR `Lvalue`s.

**Comment by oli-obk** [comment]
That's what mark_packed does. see #108

**Comment by oli-obk** [comment]
We could store  the deduced alignment in miri's lvalues. It would be the same semantics, just a different way to impl it. Feel free to open an issue about it assign it to me

**Comment by eddyb** [comment]
Oh wow I didn't realize it got set and reset... that's quite something.

**Comment by dwrensha** [comment]
I'm having trouble understanding where exactly this approach runs into trouble.

@eddyb or @oli-obk: could you show me an example program on which this approach is incorrect?

> The current code allows later writes and reads with large alignments even though it shouldn't

Could you elaborate? The following program tries to read from the value with a larger alignment and errors out, as expected.

```rust
// test.rs

pub fn main() {
    let bytes: [u8; 8] = unsafe { ::std::mem::transmute(0u64) };
    let _: &[u8] = &bytes;
    let p = bytes.as_ptr() as *const u32;
    let _ = unsafe { *p };
}
```


```
$ cargo run --bin miri -- test.rs 
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
     Running `target/debug/miri test.rs`
error: tried to access memory with alignment 1, but alignment 4 is required
 --> test.rs:7:22
  |
7 |     let _ = unsafe { *p };
  |                      ^^
  |
note: inside call to main
 --> test.rs:3:1
  |
3 | / pub fn main() {
4 | |     let bytes: [u8; 8] = unsafe { ::std::mem::transmute(0u64) };
5 | |     let _: &[u8] = &bytes;
6 | |     let p = bytes.as_ptr() as *const u32;
7 | |     let _ = unsafe { *p };
8 | | }
  | |_^

error: aborting due to previous error(s)

thread 'main' panicked at 'Box<Any>', /checkout/src/librustc_errors/lib.rs:514
```

**Comment by oli-obk** [comment]
Oh right, you create an intermediate alloc. At the minimum we'd need a test transmuting from a packed struct to something with an alignment and a test doing the opposite.

Also I'm wary about the deallocate... the previous code didn't have that. You're freeing some random memory in case it was byref before. Try creating an int variable instead of passing a const directly and reference the variable to make it an allocation and then transmute the variable. Then print the variable, miri'll probably crash in that case.

In general I'd consider the mark_packed approach cleaner, since it mimics what's supposed to happen.

**Comment by dwrensha** [comment]
> You're freeing some random memory in case it was byref before. 

Oops! Good catch. I've pushed a commit that fixes that case.

**Comment by dwrensha** [comment]
After making this change, I think that #187 is cleaner.

**Comment by oli-obk** [comment]
Yea. I think so, too. Closing this one in favour of your other PR

**Pull request closed without merging**
