### PR TITLE
Re-do memory locking

### PR DESCRIPTION
**Pull request by RalfJung**
Now with proper support for multiple independent shared borrows of the same mutable reference.

### CODE REVIEW

**Comment by oli-obk** [comment]
I'm slightly unhappy about the lack of tests for `RangeMap`.

Validation logic is a blackbox to me, but nicely commented and contains nothing that looked weird to me.

Can you run a rustfmt on librustc_miri and miri once all your changes are merged?

**Comment by RalfJung** [comment]
> I'm slightly unhappy about the lack of tests for RangeMap.

Agreed. There is no precedent for unit tests in miri (and not much in rustc either...), but I do want to look into this. Will file an issue.

> Can you run a rustfmt on librustc_miri and miri once all your changes are merged?

I thought that's what your other PR does...?

**Comment by oli-obk** [comment]
> I thought that's what your other PR does...?

Oh is this all of your changes? I'll do it tomorrow then, don't write anything new that I'll break :P

**Comment by RalfJung** [comment]
Yes, that's the stuff I still had locally. I thought I would have to fix this, but miraculously, the test suite worked the first time I tried it... something is wrong here, but so far, I don't know what.^^

> don't write anything new that I'll break :P

I have "write a bunch of compile-fail tests for validity" on my TODO list for today. If I don't find new bugs, that should not interact with your formatting. :D

**Comment by RalfJung** [comment]
So is this blocked on having unit tests for RangeMap or should I do that later in a separate PR?

**Comment by oli-obk** [comment]
> So is this blocked on having unit tests for RangeMap or should I do that later in a separate PR?

nah, not blocked. But creating some in the future is a good idea

**Comment by RalfJung** [comment]
> don't write anything new that I'll break :P

I found some bugs which I am working on now. So I again have a branch of stuff I cannot push yet... :/
I pushed what I got to <https://github.com/RalfJung/miri/tree/mir-validate>.

**Comment by oli-obk** [comment]
I think it'll be way easier if you simply include a formatting commit (no need to do any manual stuff, just run rustfmt) in your next PR. That way nothing breaks for you. The manual stuff is mainly comments, so that should be easy to rebase over.

**Comment by RalfJung** [comment]
Okay. Of course, right now you also have a PR in flight.

Maybe we'll just have some night later this week where nothing is in flight, and then we can quickly do this. ;)

**Pull request merged**
