### PR TITLE
add cargo-miri subcommand

### PR DESCRIPTION
**Pull request by oli-obk**
most code stolen from clippy.

`cargo miri` runs the project through miri instead of on the host machine

`cargo miri test` runs all tests, output is still wonky though (includes build hash and item index)

### CODE REVIEW

**Comment by solson** [comment]
Looks okay to me, but you included the changes from https://github.com/solson/miri/pull/103.

**Comment by oli-obk** [comment]
removed the unrelated changes

**Comment by solson** [comment]
Travis failed. Maybe we need to set the `PATH`?

**Comment by oli-obk** [comment]
it was just travis-cargo not support new subcommands

**Pull request merged**
