### PR TITLE
Remove unchecked_shr/shl from intrinsics

### PR DESCRIPTION
**Pull request by TimDiekmann**
r? @RalfJung

[This PR](https://github.com/rust-lang/rust/pull/53991) adds a check in the intrinsics itself. It's not needed anymore.

### CODE REVIEW

**Comment by RalfJung** [comment]
https://github.com/rust-lang/rust/pull/53697 also implemented some other intrinsics, could you remove those as well?

**Comment by TimDiekmann** [comment]
Do I assume correctly when rust-lang/rust#53991 was merged and landed on the latest nightly, the tests will pass?

**Comment by RalfJung** [comment]
Thanks!

> Do I assume correctly when rust-lang/rust#53991 was merged and landed on the latest nightly, the tests will pass?

Basically, yes -- except you will also have to update the `rust-toolchain` file in this repo to specify said nightly.

**Comment by TimDiekmann** [comment]
> Basically, yes -- except you will also have to update the `rust-toolchain`
> file in this repo to specify said nightly.

I may change this when the new nightly lands.

**Comment by TimDiekmann** [comment]
rust-lang/rust#53991 was merged, however with `nightly-2018-09-08` it fails to compile:
```none
error[E0277]: the trait bound `for<'a> MemoryData<'_>: rustc_data_structures::stable_hasher::HashStable<rustc::ich::StableHashingContext<'a>>` is not satisfied
   --> src/lib.rs:281:18
    |
281 | impl<'mir, 'tcx> Machine<'mir, 'tcx> for Evaluator<'tcx> {
    |                  ^^^^^^^^^^^^^^^^^^^ the trait `for<'a> rustc_data_structures::stable_hasher::HashStable<rustc::ich::StableHashingContext<'a>>` is not implemented for `MemoryData<'_>`
```

**Comment by RalfJung** [comment]
Actually never mind -- miri shouldn't have any `Hash` or `StableHash` implementation.  So once https://github.com/rust-lang/rust/pull/54076 lands, you should be good.

**Comment by RalfJung** [comment]
I pushed a commit to this PR that makes miri compile again once https://github.com/rust-lang/rust/pull/54076 lands.

**Pull request merged**
