### PR TITLE
Mir validate

### PR DESCRIPTION
**Pull request by oli-obk**
I rebased your branch and ripped out the "broken" code. When you continue working on it you should be able to simply revert 08dca1fbf47c68c63e5492948b756570d0a36152, git should take care of most of the other things.

r? @RalfJung

### CODE REVIEW

**Comment by RalfJung** [comment]
Wow, thanks for doing the rebase! I'll update my branch ASAP.

Regarding this PR, I feel like ti is deleting more than is necessary, isn't it? In particular, it deletes most of validate.rs, which will make this commit impossible to rebase around anything I do.

**Comment by oli-obk** [comment]
Feel free to undo the last commit and retry. But I think all validate functions require things from your modified rust

**Comment by oli-obk** [comment]
Note: you can directly edit this PR's branch

**Comment by RalfJung** [comment]
I updated the PR to match my branch and significantly shrunk the "disable" patch.

**Comment by oli-obk** [comment]
Haha right. It's that simple...

**Comment by RalfJung** [comment]
Thanks :)

**Pull request merged**
