### PR TITLE
Intrinsics and overflow

### LINKED ISSUE #151: Bitshift overflow doesn't panic
see #150 for a list of run-fail tests that finish successfully

removing https://github.com/solson/miri/blob/master/src/operator.rs#L181-L195 should solve it, PR incoming

### PR DESCRIPTION
**Pull request by oli-obk**
fixes #151

### CODE REVIEW

**Comment by solson** [comment]
Hmm, but I think we are supposed to always mask the shift width...

Compare the Debug and Release mode MIR and LLVM IR here: https://is.gd/LglRp7

Debug mode uses `CheckedShl` and an `assert` MIR statement on the overflow result, while Release uses a plain `Shl`. Both do a shift width mask in the LLVM IR, but only Debug mode can panic (from the `assert`).

So I think we need to leave the code for `Shl` alone and change something for `CheckedShl`?

**Comment by solson** [comment]
Oh, I guess this code handles both `Shl` and `CheckedShl`. Maybe we just need to adjust the cases where the overflow result is `true` to make sure the `assert` is triggered.

**Comment by oli-obk** [comment]
In debug mode, the mir shows a concrete assert. In the release mode, we still forward and the masking is done by the forwarded to function. The masking was entirely redundant

**Comment by solson** [comment]
Ohhh. In release mode we still use the `checked_shl` intrinsic and *that* does the masking?

**Comment by solson** [comment]
Huh, TIL the masking is done in std code, not the LLVM backend: https://doc.rust-lang.org/stable/src/core/num/mod.rs.html#1092-1094

**Pull request merged**
