### PR TITLE
test that we check the layout constraints as early as we can

### PR DESCRIPTION
**Pull request by RalfJung**

### CODE REVIEW

**Comment by oli-obk** [comment]
This is fun, I'm in libcore right there right now and the `Clone` impl is unsound if it calls `T::clone`

**Comment by RalfJung** [comment]
*lol* because it doesn't get a guarantee that the result is non-0?  I was wondering if we had any lingering problems like that from the missing safety check. ;)

**Comment by oli-obk** [comment]
Luckily we have a `Copy` bound, so the `Clone` impl generated just does `NonZero(self.inner)` instead of calling `Clone`, but still, I had a scare for a second there

**Comment by oli-obk** [comment]
Also this predates the attribute. `NonZero` always was compiler-hackery.

**Pull request merged**
