### PR TITLE
Stacked Borrows beautififcation, update for EscapeToRaw

### PR DESCRIPTION
**Pull request by RalfJung**
Matches https://github.com/rust-lang/rust/pull/55716 which has landed and should be in the next nightly.

### CODE REVIEW

**Comment by shepmaster** [comment]
> I don't have to wait another night

Looks like *I'll* be the one waiting another night 😝

**Comment by RalfJung** [comment]
This should work against the currently nightly now, and hence is ready for landing.

**Comment by oli-obk** [comment]
Travis is unhappy

> constant evaluation error: Borrow being accessed (Shr(None)) does not exist on the stack, or is guarded by a barrier

**Comment by RalfJung** [comment]
Interesting, probably one of those test failures that only happen *without* full MIR? (The libstd then doesn't have retag/escape-to-raw.)

**Comment by RalfJung** [comment]
Yeah, that's it. Quite a few tests though. I see two options:

* Move them to fullmir.
* Do not do validation when we have a libstd without full MIR. Though then we should be careful that people do not think validation *was* checked when truly, it was not. Maybe require a `-Zmiri-libstd-without-mir` flag to even work without full MIR?

**Comment by RalfJung** [comment]
It still makes some sense without stacked borrows (but there is no switch to disable stacked borrows but keep validation enabled, and too many switches might also be confusing).

Before dropping support for missing MIR, I'd like to have `cargo miri setup` or so which automatically does all the steps to build the libstd with full MIR. I hope to implement that next week.

**Comment by RalfJung** [comment]
With these changes, the test suite passes without full MIR locally. Let's see what Travis says.

**Pull request merged**
